# Generated by Django 3.0 on 2022-07-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20220706_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(default=101, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('yearly_free', models.IntegerField(default=50000)),
                ('est_date', models.DateField()),
            ],
            options={
                'db_table': 'College',
            },
        ),
    ]
